apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: highway63-app-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: highway63-app-deployment # Replace with your deployment name
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
