apiVersion: v1
kind: Service
metadata:
  name: highway63-app-service
  namespace: production
spec:
  type: LoadBalancer
  selector:
    app: highway63-app # Replace with your app label
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080 # Replace with your application port
